import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class shop{
	public static void main(String[] args) {
		File data = new File(args[0]);
		Scanner input = null;
		try{
			input = new Scanner (data);
		}
		catch (FileNotFoundException e) {
			System.err.println("Error: the file cannot be opened.\n");
			System.exit(1);
		}
		int totalNumber = input.nextInt();
		int[][] newArray = new int[totalNumber][2];
		int i = 0;
		while (input.hasNextInt()) {
			int temp1 = input.nextInt();
			int temp2 = input.nextInt();
			newArray[i][0] = temp1;
			newArray[i][1] = temp2;
			i++;
		}
	for (int j = 0; j < newArray.length; j++) {
		System.out.println("--------");
		for (int k = 0; k < newArray[j].length; k++) {
			System.out.print("||");
			System.out.print(newArray[j][k]);
		}
		System.out.print("||\n");		
	}
	System.out.println("--------");
	input.close();
	
	// The First Statistic
	System.out.println();
	System.out.println("1. Total number of purchases for each nationality");
	for (int n =0; n < 5; n++) {
		System.out.print(countryTotal(newArray, n));
		System.out.print(" ");
	}
	System.out.println(); 
	// The Second Statistic
	System.out.println();
	System.out.println("2. Most popular item for each nationality");
	System.out.print("Most popular item for each nationality in numerical order: \n");
	for (int n =0; n < 5; n++) {		
		System.out.print(popularByCountry(newArray, n));
		System.out.print(" ");
	}
	System.out.println();
	// The Third Statistic
	System.out.println();
	System.out.println("3. Most and least popular item number over all ");
	int[] popularity = generalPopularity(newArray);
	System.out.print("The most popular item is:");
	System.out.print(popularity[0]);
	System.out.println();
	System.out.print("The least popular item is:");
	System.out.print(popularity[1]);
	System.out.println();
	//The Fourth Statistic
	System.out.println();
	System.out.println("4. How much of each item was sold today");
	System.out.println("In the numerical order of items 0 to 9:");
	int[] sales = itemCount(newArray);
	for (int m = 0; m < 10; m++) {
		System.out.print(sales[m]);
		System.out.print(" ");
		
	}
	
	
	
	
	
	
	
	
	}
	
	/**
	 * This method finds the total purchases in a certain country
	 * @param newArray the array generated by reading the file
	 * @param countryCode the country code given
	 * @return the value of total purchases in a given country
	 */
	public static int countryTotal(int[][] newArray, int countryCode) {
		int returnValue = 0;
		for (int j = 0; j < newArray.length; j++) {
			if (newArray[j][0] == countryCode) {
				returnValue++;
			}
		}
		return returnValue;
	}
	
	/**
	 * This method finds the most popular item by country
	 * @param newArray the array generated by reading the file
	 * @param countryCode the given country code
	 * @return the most popular item
	 */
	public static int popularByCountry(int[][] newArray, int countryCode) {
			int temp = 0;
			int count = 0;
			int pointer = 0;
			for (int j = 0; j < newArray.length; j++) {
				if (newArray[j][0] == countryCode) {
					for (int k = 0; k < 9; k++) {
						if (newArray[j][1] == k) {
							count++;
						}
						if (count > temp) {
							temp = count;
							pointer = k;
						}
						count = 0;
					}
			}
				
		}
		return pointer;
	}
	
	/**
	 * This method finds the most popular and least popular item in general
	 * @param newArray the array generated by reading the file
	 * @return the array with two values: the most popular item and least popular item
	 */
	public static int[] generalPopularity(int[][] newArray) {
		int[] returnArray = new int[2];
		int current = 0;
		int currentPointer = 0;
		int pointer = 0;
		for (int countryCode = 0; countryCode < 5; countryCode++) {
			int temp = 0;
			int count = 0;
			for (int j = 0; j < newArray.length; j++) {
				if (newArray[j][0] == countryCode) {
					for (int k = 0; k < 9; k++) {
						if (newArray[j][1] == k) {
							count++;
						}
						if (count > temp) {
							temp = count;
							pointer = k;
						}
						count = 0;
					}
				}
			}
			if (current < temp) {
				current = temp;
				currentPointer = pointer;
			}
			temp = 0;
			}
			returnArray[0] = currentPointer;
			current = 0;
			currentPointer = 0;
			pointer = 0;
		
			for (int countryCode = 0; countryCode < 5; countryCode++) {
				int temp = 0;
				int count = 0;
				for (int j = 0; j < newArray.length; j++) {
					if (newArray[j][0] == countryCode) {
						for (int k = 0; k < 9; k++) {
							if (newArray[j][1] == k) {
								count++;
							}
							if (count < temp) {
								temp = count;
								pointer = k;
							}
							count = 0;
						}
					}
				}
				if (current > temp) {
					current = temp;
					currentPointer = pointer;
				}
				temp = 0;
			}
			returnArray[1] = currentPointer;
		
	return returnArray;
	}
	
	/**
	 * This method counts the number of each item sold
	 * @param newArray the array generated by reading the file
	 * @return the array of the sales value of each item in numerical order
	 */
	public static int[] itemCount(int[][] newArray) {
		int[] returnArray = new int[10];
		for (int i = 0; i < 10; i++) {
			int returnValue = 0;
			for (int j = 0; j < newArray.length; j++) {
				if (newArray[j][1] == i) {
					returnValue++;
				}
		}
			returnArray[i] = returnValue;
			i++;
	}
		return returnArray;
	}
	
	
}